import SessionInitializer from "@/features/auth/components/SessionInitializer";
import Header from "@/features/shared/components/Header";
import QueryProvider from "@/providers/QueryProvider";
import StateProvider from "@/providers/StateProvider";
import { ReactFlowProvider } from "@xyflow/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`font-nanum antialiased`}>
        <ReactFlowProvider>
          <QueryProvider>
            <StateProvider>
              <SessionInitializer />
              <Header />
              {children}
            </StateProvider>
          </QueryProvider>
        </ReactFlowProvider>
      </body>
    </html>
  );
}
